# Generated by Django 5.0.4 on 2024-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatroom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='contains_code',
            field=models.BooleanField(default=False),
        ),
    ]
