# Generated by Django 5.0.4 on 2024-05-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chat_contains_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contains_code',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='created_at',
        ),
    ]
